### ISSUE TITLE
postcss-import error when build with npm

### ISSUE THREAD

**Issue by xubeiyan** [xubeiyan/shiro-pad#1]
使用`npm`进行`build`时，报错
```
[vite:css] [postcss] postcss-import: C:\Users\yyd\Documents\playground\shiro-pad\shiro-pad\node_modules\@skeletonlabs\skeleton\dist\styles\partials\core.css:3:1: `@layer base` is used but no matching `@tailwind base` directive is present.
file: C:/Users/yyd/Documents/playground/shiro-pad/shiro-pad/node_modules/@skeletonlabs/skeleton/dist/styles/skeleton.css:3:1
error during build:
CssSyntaxError: [postcss] postcss-import: C:\Users\yyd\Documents\playground\shiro-pad\shiro-pad\node_modules\@skeletonlabs\skeleton\dist\styles\partials\core.css:3:1: `@layer base` is used but no matching `@tailwind base` directive is present.
    at Input.error (C:\Users\yyd\Documents\playground\shiro-pad\shiro-pad\node_modules\postcss\lib\input.js:106:16)
    at AtRule.error (C:\Users\yyd\Documents\playground\shiro-pad\shiro-pad\node_modules\postcss\lib\node.js:115:32)
    at normalizeTailwindDirectives (C:\Users\yyd\Documents\playground\shiro-pad\shiro-pad\node_modules\tailwindcss\lib\lib\normalizeTailwindDirectives.js:72:32)
    at C:\Users\yyd\Documents\playground\shiro-pad\shiro-pad\node_modules\tailwindcss\lib\processTailwindFeatures.js:30:98
    at plugins (C:\Users\yyd\Documents\playground\shiro-pad\shiro-pad\node_modules\tailwindcss\lib\plugin.js:38:63)
    at LazyResult.runOnRoot (C:\Users\yyd\Documents\playground\shiro-pad\shiro-pad\node_modules\postcss\lib\lazy-result.js:357:16)
    at LazyResult.runAsync (C:\Users\yyd\Documents\playground\shiro-pad\shiro-pad\node_modules\postcss\lib\lazy-result.js:286:26)
    at async compileCSS (file:///C:/Users/yyd/Documents/playground/shiro-pad/shiro-pad/node_modules/vite/dist/node/chunks/dep-439026c8.js:38783:25)
    at async Object.load (file:///C:/Users/yyd/Documents/playground/shiro-pad/shiro-pad/node_modules/vite/dist/node/chunks/dep-439026c8.js:38735:32)
    at async Promise.all (index 0)
```

但翻了`skeleton`的github issue他们表示不是他的锅，是`vite`的
https://github.com/skeletonlabs/skeleton/issues/1731
提出的解决方法是降级`vite`至4.3.9

如果你有好的解决方案，可以在下面贴出来

但自己使用的是`pnpm`，还没有发现这个问题，成功`build`

**Comment by xubeiyan** [comment]
`vite`在`v4.4.2`已经修复了这个问题，`package.json`中`vite`版本提升至`v4.4.4`
